#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Import the OM-84 rhythm patterns and wave shapes from Chordian (Jan125/pb.chordian, CC0 1.0)
into firmware/src/dsp/om_data.h. Run once; the header is checked in.

  tools/import_chordian.py PATH/TO/pb.chordian firmware/src/dsp

Chordian is a PureBasic OM-84 emulator. Its patterns are 32 sixteenth-note steps (24 for Waltz
and Blues). Per step: the bass envelope command, the chord envelope command, which drums hit,
and which bass note (root, fifth or third). Its single-cycle waves are 100 floats each; its five
drum sounds (44.1 kHz float) become 16-bit tables in om_drums.h."""
import re
import struct
import sys
from pathlib import Path

src = Path(sys.argv[1])
mh = (src / "_src" / "chordian_machinehandler.pbi").read_text(encoding="utf-8-sig")
start = mh.index(";---Rock1")
mh = mh[start - 3000:mh.index(";-Knob Data")]      # the pattern section (Rock1 begins a little before its tag)
mh = mh[mh.index("For s = 0 To 1"):]

ORDER = ["Rock1", "Rock2", "Disco", "Latin", "Country", "March", "Tango", "Blues", "Swing", "Waltz"]
ALT = {"Rock1": 0, "Rock2": 0, "Disco": 0, "Latin": 0, "Country": 0,
       "March": 1, "Tango": 1, "Blues": 1, "Swing": 1, "Waltz": 1}
DRUMS = ["BD", "Click", "HiHat", "Ride", "Snare"]
CURVE = {"Trigger": "T", "Release": "R", "Oneshot": "O", "None": "N"}

pat = {r: {"bass": ["-"] * 32, "chord": ["-"] * 32, "drum": [0] * 32, "freq": ["R"] * 32} for r in ORDER}
rx = re.compile(r"\\Data_Patterns\((\d), #Rhythm_(\w+), [in], ([0-9+ ]+), #Pattern_(\w+)\) = #Curve_(\w+)")
for m in rx.finditer(mh):
    r, step, field, curve = m.group(2), eval(m.group(3)), m.group(4), m.group(5)
    p = pat[r]
    if field == "Bass":
        p["bass"][step] = CURVE[curve]
    elif field == "Chords":
        p["chord"][step] = CURVE[curve]
    elif field.startswith("Drum_"):
        p["drum"][step] |= 1 << DRUMS.index(field[5:])

# bass note per step: Case ranges -> 2 (fifth) / 3 (third); the rest the root
blocks = re.split(r";---(\w+)", mh)
for name, body in zip(blocks[1::2], blocks[2::2]):
    if name not in pat:
        continue
    sel = body[body.find("Select i"):]
    for m in re.finditer(r"Case ([0-9+ ,To]+)\n\s*\\Data_Patterns\(\d, #Rhythm_\w+, n, i, #Pattern_Frequency\) = (\d)", sel):
        val = "5" if m.group(2) == "2" else "3"
        for part in m.group(1).split(","):
            a, _, b = part.partition("To")
            for s in range(eval(a), eval(b or a) + 1):
                pat[name]["freq"][s] = val
NAME = {"Rock1": "Rock 1", "Rock2": "Rock 2", "Disco": "Disco", "Latin": "Latin", "Country": "Country",
        "March": "March", "Tango": "Tango", "Blues": "Blues", "Swing": "Swing", "Waltz": "Waltz"}
LEN = {r: 24 if r in ("Waltz", "Blues") else 32 for r in ORDER}
out = ["/* SPDX-License-Identifier: GPL-3.0-only */",
       "/* Generated by tools/import_chordian.py from Chordian (github.com/Jan125/pb.chordian, CC0 1.0),",
       " * Jan125's OM-84 emulator: the ten rhythms and the single-cycle waves. Do not edit by hand. */",
       "#pragma once", "#include <stdint.h>", "#include \"omni.h\"", "",
       "/* a rhythm step: bass and chord envelope command (T trigger, R release, O one-shot, N cut,",
       " * '-' nothing), the bass note (R root, 5 fifth, 3 third) and the drums (bit: OM_BD..OM_SD) */",
       "enum { OM_BD, OM_CLICK, OM_HH, OM_RIDE, OM_SD, OM_NDRUM };",
       "/* om_rhythm_t: omni.h */",
       f"#define OM_NRHYTHM {len(ORDER)}",
       "static const om_rhythm_t OM_RHYTHM[OM_NRHYTHM] = {"]
for r in ORDER:
    p, n = pat[r], LEN[r]
    out.append(f'    {{"{NAME[r]}", {n}, {ALT[r]}, "{"".join(p["bass"][:n])}", "{"".join(p["chord"][:n])}",')
    out.append(f'     "{"".join(p["freq"][:n])}",')
    out.append("     {" + ", ".join(str(v) for v in p["drum"][:n]) + "}},")
out.append("};")
out.append("")
for w in ("harp", "harp_base", "harp_mod", "chord", "bass_base", "bass_mod"):
    d = (src / "_src" / "snd" / f"chordian_{w}.raw").read_bytes()
    x = struct.unpack("<100f", d)
    out.append(f"static const float OM_WAVE_{w.upper()}[100] = {{")
    for i in range(0, 100, 10):
        out.append("    " + ", ".join(f"{v:.5f}f" for v in x[i:i + 10]) + ",")
    out.append("};")
out_dir = Path(sys.argv[2])
(out_dir / "om_data.h").write_text("\n".join(out) + "\n")

drums = ["/* SPDX-License-Identifier: GPL-3.0-only */",
         "/* Generated by tools/import_chordian.py: Chordian's five rhythm sounds (CC0 1.0), 16-bit, 44.1 kHz. */",
         "#pragma once", "#include <stdint.h>", ""]
names = []
for d in ("bd", "click", "hihat", "ride", "snare"):
    raw = (src / "_src" / "snd" / f"chordian_drum_{d}.raw").read_bytes()
    x = struct.unpack("<%df" % (len(raw) // 4), raw)
    while len(x) > 1 and abs(x[-1]) < 1e-4:          # trailing silence
        x = x[:-1]
    q = [max(-32767, min(32767, round(v * 32767))) for v in x]
    drums.append(f"static const int16_t OM_DRUM_{d.upper()}[{len(q)}] = {{")
    for i in range(0, len(q), 16):
        drums.append("    " + ", ".join(str(v) for v in q[i:i + 16]) + ",")
    drums.append("};")
    names.append(d.upper())
drums.append("static const int16_t *const OM_DRUM[5] = {" + ", ".join(f"OM_DRUM_{n}" for n in names) + "};")
drums.append("static const uint32_t OM_DRUM_LEN[5] = {" + ", ".join(f"sizeof OM_DRUM_{n} / 2" for n in names) + "};")
(out_dir / "om_drums.h").write_text("\n".join(drums) + "\n")
